### ISSUE TITLE
how is the Soundbridge supposed to be discovered?

### ISSUE THREAD

**Issue by lclem** [tsibley/soundbridge#4]
when launching `soundbridge-upnp-play` it says

```
Unable to find the destination 'Soundbridge'
```

(Note that `soundbridge-whois` works correctly.)

How should I have the Soundbridge be discovered  by `soundbridge-upnp-play`?

**Comment by tsibley** [comment]
`soundbridge-upnp-play` discovers the Soundbridge via UPnP, a standardized protocol for interacting with media players over a network. If it can't find the Soundbridge on your network, then maybe UPnP isn't enabled on your Soundbridge? I forget if it has to be enabled specifically or not. It's been a long time since I've used the UPnP tools in this project.

`soundbridge-whois` assumes by default that the Soundbridge is accessible at the mDNS/Avahi/Zeroconf address `soundbridge.local`, so "discovers" the Soundbridge a different way.
